version: '3.2'
#version 3.2 will fix issue about 'attachable Additional property attachable is not allowed'
#docker stack deploy -c docker-compose.yml <name>

services:
  api:
    image: digeer/backend-nodejs:0.1.0
    deploy:
      placement:
        constraints: [ node.role == worker ]
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
      restart_policy:
        condition: on-failure
    ports:
      - 8080:8080
    networks:
      - webnet

  web:
    image: digeer/react-nginx:0.1.4
    deploy:
      placement:
        constraints: [ node.role == worker ]
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
      restart_policy:
        condition: on-failure
    ports:
      - 90:80
    networks:
      - webnet
    depends_on:
      - api

  registry:
    image: registry
    ports:
      - 5000:5000
    volumes:
      - /opt/data/registry:/var/lib/registry
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [ node.role == manager ]

networks:
  webnet:
